# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0003_summaryparagraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryparagraph',
            name='adventure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adventures.Adventure'),
        ),
        migrations.AlterField(
            model_name='summarysentence',
            name='adventure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adventures.Adventure'),
        ),
    ]
