# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0005_auto_20170420_1838'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='summaryparagraph',
            table=None,
        ),
        migrations.AlterModelTable(
            name='summarysentence',
            table=None,
        ),
    ]
