# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0006_auto_20170420_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summaryparagraph',
            old_name='description',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='summarysentence',
            old_name='description',
            new_name='text',
        ),
    ]
