# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0007_auto_20170420_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterOutline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('background', models.TextField()),
                ('personality', models.TextField()),
                ('motive', models.TextField()),
                ('conflict', models.TextField()),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.Adventure')),
            ],
        ),
    ]
