# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0009_auto_20170421_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteroutline',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
